esphome:
  name: question-block-lamp
  friendly_name: Question Block Lamp

globals:
  - id: alert_running
    type: bool
    initial_value: 'false'

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    pin:
      number: 1
      mode: INPUT_PULLUP
      inverted: true
    id: light_state
    internal: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

switch:
  - platform: gpio
    pin: 3
    id: light_toggle
    internal: true 
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Question Block Lamp Light"
    id: lamp_light
    optimistic: true
    restore_mode: ALWAYS_OFF
    lambda: |-
      return id(light_state).state;
    
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_off: light_state
          then:
            - switch.turn_on: light_toggle
            - delay: 200ms
            - switch.turn_off: light_toggle
            
    turn_off_action:
      - if:
          condition:
            binary_sensor.is_on: light_state
          then:
            - switch.turn_on: light_toggle
            - delay: 200ms
            - switch.turn_off: light_toggle

button:
  - platform: template
    name: "Question Block Lamp Alert"
    icon: mdi:bell-alert-outline
    on_press:
      - if:
          condition:
            lambda: 'return !id(alert_running);'
          then:
            - globals.set:
                id: alert_running
                value: 'true'
            - repeat:
                count: 5
                then:
                  - switch.turn_on: lamp_light
                  - delay: 1s
                  - switch.turn_off: lamp_light
                  - delay: 1s
            - globals.set:
                id: alert_running
                value: 'false'